name: Run Tests

on:
    push:
        branches:
            - feature/examen
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - uses: actions/checkout@v3

            # Set up Node.js
            - uses: actions/setup-node@v3
              with:
                  node-version: '16'

            # Install dependencies
            - run: npm install

            # Run linter (optional, if you have ESLint configured)
            - name: Run Linter
              run: npm run lint

            # Run tests with coverage
            - name: Run Tests
              run: npm run test -- --coverage
